### PR TITLE
fix: additional empty line from generated README.md

### LINKED ISSUE #177: helm-docs write extra empty line
I tried to find the right place in the code but wasn't able to determine what is causing it.

To reproduce, just run `helm-docs` against this repo. All the generated `README.md` have 2 empty lines.

image

### PR DESCRIPTION
**Pull request by jlec**
Fixes #177

### CODE REVIEW

File: pkg/document/generate.go [hunk 1]
```diff
@@ -5,6 +5,7 @@ import (
 	"os"
 	"path/filepath"
 	"regexp"
+	"strings"
```
Comment (Nepo26) [inline pkg/document/generate.go:8]: You don't need to add new dependencies

File: pkg/document/generate.go [hunk 2]
```diff
@@ -77,6 +78,7 @@ func applyMarkDownFormat(output bytes.Buffer) bytes.Buffer {
 
 	re = regexp.MustCompile(`\n{3,}`)
 	outputString = re.ReplaceAllString(outputString, "\n\n")
```
Comment (Nepo26) [inline pkg/document/generate.go:80]: You could just remove one line break that it works as you intended.

```suggestion
	outputString = re.ReplaceAllString(outputString, "\n")
```

File: pkg/document/generate.go [hunk 3]
```diff
@@ -77,6 +78,7 @@ func applyMarkDownFormat(output bytes.Buffer) bytes.Buffer {
...
+	outputString = strings.TrimSuffix(outputString, "\n")
```
Comment (Nepo26) [inline pkg/document/generate.go:81]: This is unnecessary

**Review by Nepo26 — CHANGES_REQUESTED** [review]
There is no need to add "strings" and trim the suffix. You may just remove one line break. @jlec

File: pkg/document/generate.go (hunk 2 above)
Comment (jlec) [reply pkg/document/generate.go:80]: This logic is replacing all triple or more newlines to two. With your change, we reduce it to 1. Does this make sense? Or is it better just to clean the double newlines at the EOF?

Comment (Nepo26) [reply pkg/document/generate.go:80]: Make the change and see the test charts. In principle it doesn't affect that much. 

But you are right, it could break and the way to less affect it is by using the strings as you did.

Comment (Nepo26) [reply pkg/document/generate.go:80]: I will just resolve this and accept as I see why you did it and there is no reason for such a lengthy discussion over formatting lines.
